### ISSUE TITLE
Day1

### ISSUE THREAD

**Issue by eastOffice** [ASE-couplet/frontend#1]
1. vue.js 部分的代码要放到下面，不然会报错： cannot find el: #upload
2. onchange update 没有被执行，需要解决

**Comment by Smart-Hypercube** [comment]
1. 这样想来，放在 `head` 中是否更好？因为 JS 的规则好象是，放在 `body` 中的，被执行的时间就是解析到该处的时间，如果早于相应元素就失败了，而放在 `head` 中的，应该是等解析结束才执行的吧？
1. 应该是 `label` 的问题，我已经在评论中提到了
