### ISSUE TITLE
“今日诗景”做法不对

### ISSUE THREAD

**Issue by Smart-Hypercube** [ASE-couplet/frontend#7]
请撤销 67eb023fefbf75c1c9cd335f62b6a8a1c93529a5 这次提交做的所有改动

正确的做法是正常上传图片并做出来诗，在浏览器地址栏中看到订单号（假设为 42），然后修改首页代码，把图片的 `src` 改成 `/api/image?order=42`，把链接的 `href` 改成 `/42`。

如果对生成的诗或图片不满意，可以重复上面这个过程，或者直接去 http://poemscape.mirrors.asia/admin/ 改数据库中相应的订单内容。

**Comment by eastOffice** [comment]
不用撤销吧，只要把href="/xx" 改成订单号就行了

**Comment by Smart-Hypercube** [comment]
这几张图片无需放进仓库呀，应该删掉。另外，`src` 也改成相应订单通过 API 查询出来的图片比较好（就像上面我写的那样），不然没有一致性，有可能某一天在 admin 后台把图片改了，却惊讶地发现“首页上的图片怎么不跟着变？”导致在 debug 上花时间
